hotwax/preorder

public/index.html
=> updated title for preorder(#1w9gm4n)

changelogs/unreleased/-1xc2eqg.yml, src/views/product-details.vue
=> Implemented logic to show product variants on the basis of the selected attribute(#1xc2eqg)

changelogs/unreleased/-1ym3jwv.yml, src/views/login.vue
=> Fixed the position of input label on login page (#1ym3jwv)

src/views/settings.vue
=> updated markup(#1y2ract)

src/views/settings.vue
=> Updated the UI of settings page(#1z54hy7)

changelogs/unreleased/-21aqct8.yml, src/views/catalog.vue, src/views/login.vue, src/views/orders.vue, src/views/product-details.vue, src/views/products.vue, src/views/settings.vue
=> Removed fullscreen=true from ion-content of all pages(#21aqct8)

public/index.html
=> Added theme Color in index.html(#226cynn)

src/views/settings.vue
=> Added time-outline icon for timezone(#25k73ff)

src/App.vue, src/store/modules/user/actions.ts
=> Removed timezone mismatch alert on login(2893rqm)

src/utils/index.ts
=> Improved: position of toast from top to bottom(#2a7ut0j)

.env.example, src/api/index.ts, src/views/login.vue, src/views/settings.vue
=> Improved: code to hide option to set baseURL if value available in '.env' file (#29wgkkh).

src/views/login.vue
case insensitive Instance URL 
Closes #
=> Fixed: Instance URL should be case insensitive(#2ft61zw)

src/i18n/locales/en.json, src/views/settings.vue
=> Improved label to "eCom Store" on Settings page (#23tw4yf)

CONTRIBUTING.md, README.md
=> Update contribution guideline in Readme file(#2r0kmb3)

package-lock.json, package.json
=> Improved: app version in package and lock file for new release(#2rbz0yh)

package-lock.json, package.json, release-notes.md
=> Improved: release notes, package and lock file for 1.0.2 release(1.0.2)

package-lock.json, src/views/settings.vue
=> Added icons for eCom Store and user profile on settings page

.env.example, src/views/login.vue
=> Added support to alias specific instance URL with environment configuration(#30dkjp1)

package-lock.json, package.json
=> preparing release 1.1.0(#32cb9yy)

src/views/product-details.vue
Closes #110 
[Screencast from 07-04-23 03:21:02 PM IST.webm](https://user-images.githubusercontent.com/59442907/230587994-3eb22ace-942a-44db-ae76-b52501438fd5.webm)
=> Fixed: filtering on product details for product variants (#85zrvxuxk)

src/store/modules/order/actions.ts, src/views/products.vue
Optimized the query to search on specific fields, ** searches on all field and values
Closes #
=> Fixed: query string to search only query fields

src/store/modules/order/actions.ts, src/store/modules/user/actions.ts, src/store/modules/user/mutations.ts, src/views/settings.vue
=> Improved: App should be accessed only by users with having role with product store (#115)

package-lock.json, package.json, release-notes.md
=> Updated: app version and release-notes for minor-release(v1.3.0)

package-lock.json, package.json
=> Updated: app version for minor release (1.4.0)

src/store/modules/job/actions.ts, src/views/orders.vue, src/views/product-details.vue, src/views/warehouse-modal.vue
Additional change:
Improved code to get jobs, reset jobs if there is error with 'No jobs found' message
Closes #
=> Improved: added spinner while performing bulk actions

package-lock.json, package.json, release-notes.md
=> Updated: app version and release notes for minor release(v1.5.0)

package-lock.json, package.json
=> Updated: app version for minor release (1.5.0)

src/store/modules/order/actions.ts, src/views/products.vue
=> Improved: order and product query to allow searching using good identifications

src/store/modules/order/actions.ts, src/views/products.vue
=> Improved: added more customer specific fields for order and product specific for product query

package-lock.json, package.json, release-notes.md
=> Updated: app version and release notes for minor release(v1.6.0)

package-lock.json, package.json
=> Updated: app version for minor release (1.7.0)

src/views/catalog-product-details.vue
Closes #
Issue: The header components were packed closely together, causing spacing issues.
Solution: The header styling has been updated from "Autofill" to "Autofit" to resolve the spacing problem.
=> Fixed header styling

src/i18n/locales/en.json, src/views/catalog-product-details.vue
=> Changed section header from `Purchase order and online atp calculation` to `Presell eligibility`

src/views/catalog-product-details.vue
=> Fixed: skip showing shopify shops with no access (#147)

src/views/catalog-product-details.vue
=> Improved: Show PO external orderId (#157)

src/views/catalog.vue
=> Improved: allow searching on Catalog page with upc internalName brandName and parentProductName

src/services/JobService.ts, src/services/ShopifyService.ts, src/views/catalog-product-details.vue
=> Sort shopify shops to keep the same order for all pages and variants

package-lock.json, package.json
=> Upgraded ionic to 6.7.5 to fix popover issue with Chrome and Edge

src/views/background-job-modal.vue
=> Fixed: background jobs data failed to load due to wrong variable

src/i18n/locales/en.json, src/views/catalog-product-details.vue
Handled case when the ProductCategoryDcsnRsn records doesn't exists Implemented code to get available POs for the products not in any category
Closes #
=> Improved: logic to fetch purchase order details

src/i18n/locales/en.json, src/views/product-details.vue
=> Autofill input field on clicking `in stock` badge

src/services/JobService.ts
=> Fixed: wrong service being used for fetching background job details(#188)

src/i18n/locales/en.json, src/views/catalog-product-details.vue
=> Implemented: button to copy audit message (#182)

package-lock.json, package.json
=> Updated: app version for minor release (1.11.0)

src/store/modules/product/actions.ts
Closes #208
The loader on the Pre-order Product Summary page is used unnecessarily. Hence the loader is removed, and the existing skeleton text is used as the sole indicator of content loading.
=> Improved: Loader on the product summary page is not required hence removed it. (#208)

src/views/catalog-product-details.vue
=> Fixed: category and brokering jobs card loading if job data for any job is missing (#199)

package-lock.json, package.json
Closes #
Updated: app version for minor release (1.12.0)
=> Updated: app version for minor release (1.12.0)

src/views/catalog.vue
=> Improved: support to search products on the catalog page on search_goodIdentifications

package-lock.json, package.json
Closes #
Updated: package.json and package-lock.json for the minor release to v1.13.0.
=> Updated: package.json and package-lock.json for the minor release to v1.13.0.

package-lock.json, package.json
Closes #
Updated: package.json and package-lock.json for minor release (1.14.0)
=> Updated: package.json and package-lock.json for minor release (1.14.0)

package-lock.json, package.json
Closes #
Updated: package.json and package-lock.json for the hotfix release (1.14.1).
=> Updated: package.json and package-lock.json for the hotfix release (1.14.1).

src/store/modules/user/actions.ts
=> Implemented: parsing logic in try catch as in some case the logout api makes redirection, and then we unable to parse the resp

package-lock.json, package.json, src/views/settings.vue, vue.config.js
Related Issue: https://github.com/hotwax/dxp-components/issues/177
Used the centralized oms instance navigator on the settings page which is implemented in dxp-components.
=> Implemented: centralized oms instance navigator in settings page from dxp-components (#177)

src/views/catalog-product-details.vue
Closes #
Previously done changes were removed while resolving merge conflicts. Hence, re-opening a PR with the changes.
=> Fixed: inconsistent shopfiy shop ordering through manually sorting the shopListings on the UI (#200)

package-lock.json, package.json
Closes #
Updated: App version for minor release (1.16.0)
=> Updated: App version for minor release (1.16.0)

src/views/catalog.vue
=> Implemented: all filtering by default on catalog page (#258)

src/views/catalog.vue
Closes #264
Fixed issue of spinner not showing on product scrolling in product audit page.
=> Fixed: spinner not showing on product scrolling in audit page (#264)

src/store/modules/user/actions.ts
=> Fixed: permission issue when defining a base permission for app

src/services/OrderService.ts
#296 
#
Improved: Passed selected productStoreId while uploading file for releasing, cancelling or updating promise date.
=> Improved: Passed selected productStoreId while uploading file for releasing, cancelling or updating promise date (#296).

src/services/OrderService.ts, src/views/orders.vue, src/views/product-details.vue, src/views/promise-date-modal.vue, src/views/warehouse-modal.vue
#296 
#
Improved: Passed productStoreId in the needed format (#296).
=> Improved: Passed productStoreId in the needed format (#296).

package-lock.json, package.json
=> Improved: app version in package and lock file for patch release(v1.18.1)

package-lock.json, package.json
=> Updated: app version for minor release v1.19.0

src/main.ts, src/theme/variables.css
=> Impproved: Added support for the dark mode.

src/main.ts
=> Fixed: Build failure issue.(#312)

src/utils/index.ts, src/views/audit-product-details.vue
#319 
#
Feature title is always display a user friendly label.
=> Improved: Feature title in dynamic features support by using productFeatures.(#319)

src/views/audit-product-details.vue
=> Fixed: key accessing issue when preparing shopify listing status for the audit detail page(317)

src/views/audit.vue
#327 
- Handled the issue on the audit page where products would disappear when the user scrolls to load more.
=> Fixed: Product no longer disappears on scroll during pagination (#327)

src/i18n/locales/en.json, src/store/modules/product/actions.ts, src/views/audit-product-details.vue
#330
Added product store id check while fetching product in details page.
Added empty state if no product found.
=> Improved: fetching product detail with store check and showing empty state if not found (#330)

package-lock.json, package.json
=> Updated: app version for minor release v1.21.0
