src/views/background-job-modal.vue
src/views/edit-shipping-modal.vue
src/views/promise-date-modal.vue
src/views/timezone-modal.vue
src/views/warehouse-modal.vue

Added slot icon-only to ion-icon in ion-button(#238uwuv)

---

src/services/UserService.ts
src/store/modules/user/actions.ts

Added support to store user preference for selected brands 
- make new services setUserPref  for set the selected brand preference  and getUserPref for getting the current preferenced brand
- set User preference while selecting of brand and get User preference during login
Closes #

Implemented: support to store user preference for selected brands (#2f2h93z)

---

src/apparel-sorter/index.ts
src/main.ts
src/views/product-details.vue

Sort features (color, size etc) using apparel sorter (#2kbv95j)

---

src/store/modules/user/actions.ts

Closes #95 
Fixed eCommerce store options not appearing on the settings page. 

Fixed eCommerce options are not visible on settings page (#85zrhj216)

---

src/i18n/locales/en.json
src/views/catalog-product-details.vue

Used only ProductCategoryDcsnRsn for getting the active PO, based upon the categoryId labeled it as current or last active PO
Fixed logic to get preorder items using orderId
Improved UI to handle when there are no active or last active PO
Closes #147 

Fixed: Inconsistent Header in Purchase Order Card (#147)

---

src/i18n/locales/en.json

Internationalisation entry missing in en.json
Closes #163

Fixed: Listing failed missing date time (#163)

---

src/components/Menu.vue

Issue link: https://github.com/hotwax/dxp-components/issues/122
Fixed the issue of menu not being enabled for the correct page when using the back button in the preorder app.
- Removed a watcher from the menu component that checks for route changes
- Defined a computed property to find the correct index in the menu list
- Added an entry in the menu component pages to list all the child routes those are not listed in the menu for a specific parent route, using which we have enabled the correct menu in the UI.
- Added a logic for the dynamic child routes in the app.

Implemented: Page Selection Persistence for Preorder App  with Side Navigation (#122)

---

src/i18n/locales/en.json
src/views/catalog-product-details.vue

Closes #211
Removed 'in' from timeline message to avoid word duplication on product summary page.

Fixed: eliminated 'in' word duplication in timeline message on product summary page (#211)

---

src/views/catalog-product-details.vue

Closes #198
Previously, when fetching the shopify listing status, we were always fetching the status using shopify Id, but in some cases we list the product using third party that makes the use of HotWax product Id. So in any of the case, we should always get the status.
Added support to fetch the listing data on both shopify product id and HotWax product id.

Fixed: shopify listing to display status when listing is done directly or by third party(#198)

---

src/views/catalog-product-details.vue

Closes #225
In some cases, we are having listing information available, but the information has missing listingTime due to which the code breaks.
So, added a check for listingTime, and show the time on UI only when the time is available

Fixed: listing data not visible when listingTime information is missing(#225)

---

src/store/modules/user/actions.ts
src/views/settings.vue

Related to https://github.com/hotwax/preorder/pull/223

Improved: code to redirect the user to SSO screen when enabled otherwise redirect to launchpad on logout

---

src/views/catalog-product-details.vue

Closes #231 
Fixed solr-query to fetch Shopify config details for only the current variant by adding a check to only add product variant ID in the query if it's available. Previous query had empty variant ID being sent, hence, fetched configs for other product variants too due to ORing.

Fixed: product summary and shop listing status cards skeleton text loading (#231)

---

src/views/catalog-product-details.vue

Wrong PO information is displayed on the active PO card on the catalog page
Closes #
Changed the orderBy field to use estimatedDeliveryDate to fetch the PO information.

Fixed: the active PO information on the catalog details page

---

src/i18n/locales/en.json
src/views/background-job-modal.vue

Closes #246 
it is removing the extra the which is there in background job model empty state.

Removed extra "the" of background job model empty state(#246)

---

src/views/catalog.vue

Closes #266
Added an "All" chip for filtering all the products on the product audit page.

Improved: added an all chip for selecting all products on product audit page (#266)

---

src/views/catalog.vue
src/views/orders.vue
src/views/products.vue

https://github.com/hotwax/dxp-components/issues/289
In Ionic 7.6.0, an issue was fixed that caused infinite scroll to trigger when quickly scrolling or when items had not filled the entire page. This issue resulted in infinite scroll problems when used with search functionality. A key was added to the infinite scroll to trigger a re-render when the keyword is changed.

Fixed: infinite scroll issue when used with searchbar(dxp-289) 

---

src/views/order-popover.vue
src/views/orders.vue
src/views/product-details.vue

Improved: toFacilityId when releasing items manually from the app(#290)

---

src/views/order-popover.vue
src/views/orders.vue
src/views/products.vue

Closes #244 
I have changed the variable name to Camel Case for better readability.
**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with the description of your change

Camel Case Corrected

---

src/views/audit-product-details.vue

#317 
Improved: the payload for getShopifyConfigDetails as the Shopify's API response structure has changed.

Improved: the payload for getShopifyConfigDetails as the Shopify's API response structure has changed.(#317)

---

src/i18n/locales/en.json
src/store/modules/user/actions.ts

#305 
Enhanced permission error messaging to include missing permission details and added locales to resolve issue of error message shown is "Login failed. Please contact the administrator", which was misleading and does not accurately describe the issue.
the app now displays a clear and relevant error message indicating that the user does not have access due to the specific permission.
[Screencast from 07-03-25 06:22:23 PM IST.webm](https://github.com/user-attachments/assets/855d813c-97d8-4d39-80e5-59fba2bf2176)

Fixed: enhanced permission error messaging to include missing permission details and added locales (#305)

---

src/views/audit-product-details.vue

#328 
- The alert box now dismisses correctly after clicking the alert button.
- Added preventDefault on the event to stop the default toggle behavior of the ion-toggle.

Fixed: the alert box issue where it was not being removed after changes. (#328)

---

src/store/modules/order/actions.ts

#326 
- Fixed the issue where, while setting the promised date-time value to the order item, the conversion format was incorrect. As a result, the `formatUtcDate` utility function was returning "Invalid" instead of a valid date.

Fixed: Incorrect format used for converting the order promised date (#326)

---

src/services/ProductService.ts
src/views/audit-product-details.vue

#333 
- Previously, the category mapping wasn't working correctly because the product categories for the selected variant weren't being fetched. Added an API call to fetch the categories and correctly map them with the productStoreCategories.

Fixed: Fetched the product categories for the selected product variant (#333)
